name: example
description: An example application for the package.

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  protobuf: 3.1.0
  protoc_plugin: 21.1.2

dev_dependencies:
  build_runner: ^2.1.5
  lints: ^1.0.0
  protobuf_generator:
    path: ../

