name: protobuf_generator
description: "A flutter generator package for generating code for protobuf, without installing protoc and protoc_plugin manually"
version: 1.0.8
repository: https://github.com/TamilKannanCV/protobuf_generator

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  archive: ^4.0.7
  build: ^4.0.0
  http: ^1.5.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
