name: protobuf_generator
description: "A flutter generator package for generating code for protobuf, without installing protoc and protoc_plugin manually"
version: 1.0.6
repository: https://github.com/TamilKannanCV/protobuf_generator

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.1.6
  build: ^2.1.1
  http: ">=0.13.4 <2.0.0"
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ">=1.0.0 <3.0.0"
  test: ^1.16.0
