name: Publish to pub.dev

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Package to pub.dev
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Publish to pub.dev
        run: dart pub publish --force
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}